PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
FILTER_REGEX_EXCLUDE: (vendor/)
ENABLE:
    - BASH
    - DOCKERFILE
    - EDITORCONFIG
    - JSON
    - MARKDOWN
    - PHP
    - YAML
DISABLE_LINTERS:
    - JSON_JSONLINT
    - JSON_V8R
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - MARKDOWN_MARKDOWN_TABLE_FORMATTER
    - PHP_PHPSTAN
    - PHP_PSALM
    - YAML_V8R
DOCKERFILE_DOCKERFILELINT_ARGUMENTS: "-c /tmp/lint/.github/linters"
DOCKERFILE_HADOLINT_CONFIG_FILE: ".hadolint.yml"
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: "(\\.idea|\\.editorconfig|\\.github|\\.gitignore|LICENSE|README.md)"
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: "(composer.json)"
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ".markdown-lint.json"
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "(\\.github)"
PHP_PHPCS_CONFIG_FILE: ".phpcs.xml.dist"
PHP_PHPCS_ARGUMENTS: "-n"
PHP_PHPSTAN_CONFIG_FILE: "phpstan.neon.dist"
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "(\\.github)"
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "(\\.github)"
CONFIG_REPORTER: false
UPDATED_SOURCES_REPORTER: false
#TEXT_REPORTER: true # cannot be set to true, and should use default value (true), otherwise TAP REPORTER is also generated. See https://github.com/nvuillam/mega-linter/issues/744
CONSOLE_REPORTER: true
