---
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
EXCLUDED_DIRECTORIES: [".git", ".changes"]
IGNORE_GITIGNORED_FILES: true
ENABLE:
    - ACTION
    - BASH
    - CREDENTIALS
    - DOCKERFILE
    - EDITORCONFIG
    - JSON
    - MARKDOWN
    - PHP
    - YAML
DISABLE_LINTERS:
    - JSON_PRETTIER
    - JSON_V8R
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - MARKDOWN_MARKDOWN_TABLE_FORMATTER
    - PHP_BUILTIN
    - PHP_PSALM
    - PHP_PHPCSFIXER
    - YAML_V8R
DOCKERFILE_HADOLINT_CONFIG_FILE: ".hadolint.yml"
EDITORCONFIG_EDITORCONFIG_CHECKER_CLI_LINT_MODE: project
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ".markdown-lint.json"
PHP_PHPCS_CONFIG_FILE: ".phpcs.xml.dist"
PHP_PHPCS_ARGUMENTS: "-n"
PHP_PHPSTAN_CLI_LINT_MODE: project
PHP_PHPSTAN_DISABLE_ERRORS: true # because this project is not yet compatible with PHPStan 2.0 embedded with MegaLinter 8.2.0 or greater
PHP_PHPLINT_CLI_LINT_MODE: project
PHP_PHPLINT_ARGUMENTS: "--no-cache"
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "(\\.github|mkdocs\\.yml|\\.mega-linter\\.yml|\\.changie\\.yaml)"  # As it cannot be added in .gitignore for ML actionlint linter
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "(\\.github|mkdocs\\.yml)"  # As it cannot be added in .gitignore for ML actionlint linter
CONFIG_REPORTER: false
UPDATED_SOURCES_REPORTER: false
CONSOLE_REPORTER: true
LOG_LEVEL: INFO
PRINT_ALL_FILES: false
