PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
FILTER_REGEX_EXCLUDE: (vendor/)
ENABLE:
    - BASH
    - DOCKERFILE
    - EDITORCONFIG
    - JSON
    - MARKDOWN
    - PHP
    - YAML
DISABLE_LINTERS:
    - JSON_V8R
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - PHP_PHPSTAN
    - PHP_PSALM
    - YAML_V8R
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: "(.idea|.editorconfig|README.md)"
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: "(composer.json)"
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ".markdown-lint.json"
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILTER_REGEX_EXCLUDE: "(README.md|ROADMAP.md)"
PHP_PHPCS_CONFIG_FILE: ".phpcs.xml.dist"
PHP_PHPCS_ARGUMENTS: "-n"
PHP_PHPSTAN_CONFIG_FILE: "phpstan.neon.dist"
#APPLY_FIXES: BASH_SHFMT
