---
site_name: Docker PHP toolbox
site_url: https://llaville.github.io/docker-php-toolbox
repo_url: https://github.com/llaville/docker-php-toolbox  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository
site_author: Laurent Laville
edit_uri: ""  # hide edit button -- https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#edit-button
theme:
    name: material
    palette:  # Color palette toggle -- https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
    # editorconfig-checker-disable
        - scheme: default
          primary: cyan
          toggle:
              icon: material/lightbulb-outline
              name: Switch to dark mode
        - scheme: slate
          toggle:
              icon: material/lightbulb
              name: Switch to light mode
    # editorconfig-checker-enable
    features:
        - navigation.instant  # Instant loading -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
        - navigation.tabs  # Navigation tabs -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
        - navigation.indexes  # Section index pages -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
        - navigation.top  # Back-To-Top button -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
markdown_extensions:
    - pymdownx.highlight  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
    - pymdownx.superfences  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences
nav:
    - "Home": README.md
    - "Getting-Started": getting-started.md
    - "PHP-FPM": php-fpm.md
    - "Usage":
        - "Build Dockerfiles": usage/build-dockerfile.md
        - "Build Images": usage/build-image.md
        - "List Extensions": usage/list-extensions.md
        - "List Tools": usage/list-tools.md
    - "Contributing": contributing.md
    - "Credits": credits.md
    - "Appendix":
        - "Available extensions": appendix/extensions.md
        - "Available tools": appendix/tools.md
