---
name: GitHub-Pages

on:
    push:
        branches:
            - master
        paths:
            - docs/**
    pull_request:
    workflow_dispatch:

jobs:
    deploy:
        name: Documentation
        uses: llaville/.github/.github/workflows/gh-pages.yml@master
        with:
            destination-dir: 1.x
        secrets:
            gh-token: ${{ secrets.GITHUB_TOKEN }}
