---
name: Release

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    lint_files:
        uses: llaville/.github/.github/workflows/mega-linter.yml@master
        with:
            repository: ${{ github.repository }}
            php-version: "8.1"

    build:
        needs: lint_files

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-22.04
                php:
                    - 8.1

        steps:
            -   # Git Checkout
                name: Checkout
                uses: actions/checkout@v3

            -   # Setup PHP runtime
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   # Install Composer dependencies
                name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: "--prefer-dist"

            -   # Prepare binaries BOX Manifest commands
                name: Download BOX Manifest Artifacts
                run: |
                    cd ${{ github.workspace }}
                    curl -Ls https://github.com/llaville/box-manifest/releases/download/3.1.0/box-manifest.phar -o /usr/local/bin/box-manifest
                    chmod +x /usr/local/bin/box-manifest
                    curl -Ls https://github.com/llaville/box-manifest/releases/download/3.1.0/box-stub.phar -o /usr/local/bin/box-stub
                    chmod +x /usr/local/bin/box-stub
                    curl -Ls https://github.com/llaville/box-manifest/releases/download/3.1.0/box-compile.phar -o /usr/local/bin/box-compile
                    chmod +x /usr/local/bin/box-compile

            -   # Build the current release with artifacts (php archive)
                name: Build Release Artifact for Toolkit Application
                run: |
                    /usr/local/bin/box-manifest -c box.json --output-file=sbom.xml
                    /usr/local/bin/box-manifest -c box.json --output-file=manifest.txt --format ansi
                    /usr/local/bin/box-stub -c box.json --output-file=stub.php --resource manifest.txt --resource sbom.xml
                    /usr/local/bin/box-compile -c box.json.dist
            -
                name: Build Release Artifact for Devkit Application
                run: |
                    /usr/local/bin/box-manifest -c box-devkit.json --output-file=sbom.xml
                    /usr/local/bin/box-manifest -c box-devkit.json --output-file=manifest.txt --format ansi
                    /usr/local/bin/box-stub -c box-devkit.json --output-file=stub.php --resource manifest.txt --resource sbom.xml
                    /usr/local/bin/box-compile -c box-devkit.json.dist

            -   # Create a new Release (from a tag)
                name: Create Release from current tag
                if: github.ref_type == 'tag'
                uses: softprops/action-gh-release@v1
                with:  # https://github.com/softprops/action-gh-release#-customizing
                    prerelease: false
                    draft: true
                    body_path: ${{ github.workspace }}/.changes/${{ github.ref_name }}.md
                    # https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets
                    files: |
                        ${{ github.workspace }}/bin/toolkit.phar
                        ${{ github.workspace }}/bin/devkit.phar
                    fail_on_unmatched_files: true
                    tag_name: ${{ github.ref_name }}
