---
name: Release

on:
    push:
        branches:
            - "[0-9]+.[0-9]+"
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch:

jobs:
    lint_files:
        uses: llaville/.github/.github/workflows/mega-linter.yml@master
        with:
            repository: ${{ github.repository }}

    build:
        needs: lint_files

        uses: llaville/.github/.github/workflows/release.yml@master
        with:
            repository: ${{ github.repository }}
            box-output: ""
            release-draft: true
            release-prerelease: ${{ github.ref_type == 'branch' }}
            legacy: false
            changie-version: v1.11.0
            changie-command-args: "batch --keep --prerelease snapshot auto"
